name: "Create new hotfix"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-hotfix:
    name: "New hotfix branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        ref: main

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create hotfix branch
        run: git checkout -b hotfix/v${{ github.event.inputs.version }}

      - name: Update version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json
          git commit --message "Prepare hotfix ${{ github.event.inputs.version }}"
          git push --set-upstream origin hotfix/v${{ github.event.inputs.version }}

      - name: Create pull request to `main`
        run: gh pr create --draft --base main --title "Hotfix v${{ github.event.inputs.version }}" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request to `develop`
        run: gh pr create --draft --base develop --title "Hotfix v${{ github.event.inputs.version }} [back-merge]" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
